services:
  cpuminer:
    image: ghcr.io/c-man-the-man/cpuminer-docker-opt:latest
    container_name: cpuminer

    restart: unless-stopped

    # Docker CPU limit (optional but aligned with CPU_FRACTION)
    cpus: ${CPUS}

    init: true
    tty: true

    environment:
      CPU_FRACTION: ${CPU_FRACTION}
      POOL: ${POOL}
      WALLET: ${WALLET}
      WORKER: ${WORKER}
      PASSWORD: ${PASSWORD}
      ALGO: ${ALGO}
      EXTRA_FLAGS: ${EXTRA_FLAGS}
